### ISSUE TITLE
restaurant starter site issues

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/ti-starter-sites#1]
@rodica-andronache not sure where is best to raise starter sites related problems.

On restaurant one seems icons are missing? or there is a js error? https://www.dropbox.com/s/4qwgpmje23zm5o5/Screenshot%202019-07-29%2011.04.34.png?dl=0

I am also not sure if is best to load google maps directly since would mess a lot loading times

**Comment by rodica-andronache** [comment]
I've removed the google maps.
For the icons, I've changed them for now, but it looks to be something related to FA as well https://prnt.sc/olglcr, it can be investigated here https://github.com/Codeinwp/themeisle-companion/issues/370
