### ISSUE TITLE
Newspaper starter site

### ISSUE THREAD

**Issue by FitzChris** [Codeinwp/ti-starter-sites#2]
Hey guys,

Not sure where this request should go but...

Anca noticed a lot of people asking about a newspaper or news portal theme. I am not sure if we have something specific in the works, but it could work as a starter site.

**Comment by rodica-andronache** [comment]
Thanks, Chris! This is already in the list of ideas. We'll probably have one soon 👍 
We keep track of the starter sites in notion.so, but as not everyone has access, you can keep adding here any future ideas
